### ISSUE TITLE
Migrating azurerm_azuread resources to new azuread provider breaks the statefile

### ISSUE THREAD

**Issue by calinmarina** [terraform-providers/terraform-provider-azuread#47]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

tried both Terraform v0.11.10 and v0.11.11
Providers:
"azuread" (0.1.0)...
"azurerm" (1.21.0)...

### Affected Resource(s)

* `azuread_service_principal`

### Problem Description

Trying to follow the migration steps: 
https://www.terraform.io/docs/providers/azurerm/guides/migrating-to-azuread.html

after successfully moving the resources in the statefile with
```hcl
terraform state mv module.app_env.azurerm_azuread_service_principal.gitlab_runner_sp module.app_env.azuread_service_principal.gitlab_runner_sp
```
following
```hcl
terraform plan
```
ends up in panic with lease on statefile not being released

### Debug Output

```log
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb67f38]

goroutine 12534 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc0002fa048, 0x2, 0x2506de0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x328
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc0002fa048, 0x2edae60, 0xc0002fa048)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x6e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2edae60, 0xc0002fa048, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x9a2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00126ea80, 0x2edae60, 0xc0002fa048, 0xc000bcc140)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x367
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x986

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Panic Output

```log
2019/02/16 01:58:16 [TRACE] dag/walk: walking "module.app_env.azuread_service_principal.gitlab_runner_sp"
2019/02/16 01:58:16 [TRACE] vertex 'root.module.app_env.azuread_service_principal.gitlab_runner_sp': walking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb67f38]

goroutine 12534 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc0002fa048, 0x2, 0x2506de0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x328
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc0002fa048, 0x2edae60, 0xc0002fa048)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x6e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2edae60, 0xc0002fa048, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x9a2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00126ea80, 0x2edae60, 0xc0002fa048, 0xc000bcc140)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x367
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x986
```
### Steps to Reproduce

... I hope I'm going to have some time soon to quickly write a tf file for generating this issue although the issue is clear, I managed to overpass it although with a lot of manual intervention directly in the statefile

### Manual solution to overcome the issue

Manually solved the issue by editing the state file... 
it looks like `terraform state mv <source> <dest>` left all `azuread_` references in "depends_on" fields unmigrated like this:
```json
"depends_on": [
    "azurerm_azuread_service_principal.gitlab_runner_sp"
```
instead of
```json
"depends_on": [
    "azuread_service_principal.gitlab_runner_sp"
```
hence the panic so edit the statefile and replace all `azurerm_azuread_` occurences to `azuread_` and rerun plan

**Comment by manicminer** [comment]
@calinmarina Thanks for reporting this. I'm sure you've successfully migrated by now, but this prompted me to take a look at the [migration docs](https://www.terraform.io/docs/providers/azurerm/guides/migrating-to-azuread.html) and update them a little with additional instructions that also fixes the `depends_on` fields.

**Comment by calinmarina** [comment]
sure @manicminer, I've stitched it up before raising the ticket... problem solving was first priority then raising awareness ;)

thanks for your follow up though :+1:
